- name: Understand the facts
  hosts: centos:ubuntu
  become: yes
  tasks:
  - name: print all facts
    ansible.builtin.debug:
      msg: "All Facts: {{ansible_facts}}"

  - name: add user ubuntu
    ansible.builtin.command: adduser sakila
    when: ansible_facts['distribution'] == "ubuntu"
  
  - name: add user centos
    ansible.builtin.command: useradd sakila
    when: ansible_facts['distribution'] == "centos"