- name: Demo on filters
  hosts: localhost
  vars:
    NAME: sakila
  tasks:
  - name: convert into uppercase
    debug:
      msg: "Hello {{ NAME | upper }}"

  - name: printing undefined variables
    debug:
      msg: "Course name is : {{ COURSE | default('DevOps') }}"
